// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("clickhousetraces")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/exporter/clickhousetracesexporter"
)

const (
	TracesStability = component.StabilityLevelStable
)
