// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozddstats")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/processor/signozddstatsprocessor"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
