# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: signoz-schema-migrator

before:
  hooks:
    - go mod tidy

builds:
  - id: signoz-schema-migrator
    binary: bin/signoz-schema-migrator
    main: cmd/signozschemamigrator/main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goamd64:
      - v1
    goarm64:
      - v8.0
    mod_timestamp: "{{ .CommitTimestamp }}"

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{- .Os }}_{{- .Arch }}
    wrap_in_directory: true
    strip_binary_directory: false
    files:
      - src: conf
        dst: conf

release:
  name_template: "{{ .Tag }}"
  draft: false
  prerelease: auto
