run:
  timeout: 10m
linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
  gofmt:
    simplify: true
  gosimple:
    go: '1.18'
linters:
  enable:
    - gofmt
    - goimports
  disable:
    - staticcheck
    - typecheck
    - gosec
    - govet
    - errcheck
    - gocritic
    - revive
    - deadcode
    - gosimple
    - ineffassign
    - depguard
    - errorlint
    - structcheck
    - varcheck
    - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
