package entity

import (
	"context"
	"time"
)

// A domain entity representing a metric generated by the input.
// In order to prevent foreign key bloating, keyId is not a foreign key in
// the corresponding db representation. Validation should be taken care of
// by the application.
type LimitMetric struct {
	Period   Period
	Value    LimitValue
	Signal   Signal
	PeriodAt time.Time
	KeyId    Id
}

func NewLimitMetric(period Period, value LimitValue, signal Signal, periodAt time.Time, keyId Id) *LimitMetric {
	return &LimitMetric{
		Period:   period,
		Value:    value,
		Signal:   signal,
		PeriodAt: periodAt,
		KeyId:    keyId,
	}
}

type LimitMetricRepository interface {
	Insert(context.Context, []*LimitMetric) error
	SelectValueByPeriodAndSignalAndPeriodAtAndKeyId(context.Context, Period, Signal, time.Time, Id) (LimitValue, error)
}
