// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozjsontypeexporter")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/exporter/jsontypeexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
