// Code generated by mdatagen. DO NOT EDIT.

package jsontypeexporter

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestComponentFactoryType(t *testing.T) {
	require.Equal(t, "signozjsontypeexporter", NewFactory().Type().String())
}
