// Code generated by mdatagen. DO NOT EDIT.

package jsontypeexporter

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestComponentStability(t *testing.T) {
	factory := NewFactory()
	assert.NotNil(t, factory)
}
