// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/SigNoz/signoz-otel-collector/processor/signozlogsnormalizerprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/SigNoz/signoz-otel-collector/processor/signozlogsnormalizerprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                       metric.Meter
	mu                                          sync.Mutex
	registrations                               []metric.Registration
	SignozlogsnormalizerFieldInferences         metric.Int64ObservableCounter
	SignozlogsnormalizerMessageFlattenings      metric.Int64ObservableCounter
	SignozlogsnormalizerMessageNestedPromotions metric.Int64ObservableCounter
	SignozlogsnormalizerMessagePromotions       metric.Int64ObservableCounter
	SignozlogsnormalizerMessageStringifications metric.Int64ObservableCounter
	SignozlogsnormalizerRecords                 metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterSignozlogsnormalizerFieldInferencesCallback sets callback for observable SignozlogsnormalizerFieldInferences metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerFieldInferencesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerFieldInferences, obs: o})
		return nil
	}, builder.SignozlogsnormalizerFieldInferences)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizerMessageFlatteningsCallback sets callback for observable SignozlogsnormalizerMessageFlattenings metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerMessageFlatteningsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerMessageFlattenings, obs: o})
		return nil
	}, builder.SignozlogsnormalizerMessageFlattenings)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizerMessageNestedPromotionsCallback sets callback for observable SignozlogsnormalizerMessageNestedPromotions metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerMessageNestedPromotionsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerMessageNestedPromotions, obs: o})
		return nil
	}, builder.SignozlogsnormalizerMessageNestedPromotions)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizerMessagePromotionsCallback sets callback for observable SignozlogsnormalizerMessagePromotions metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerMessagePromotionsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerMessagePromotions, obs: o})
		return nil
	}, builder.SignozlogsnormalizerMessagePromotions)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizerMessageStringificationsCallback sets callback for observable SignozlogsnormalizerMessageStringifications metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerMessageStringificationsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerMessageStringifications, obs: o})
		return nil
	}, builder.SignozlogsnormalizerMessageStringifications)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizerRecordsCallback sets callback for observable SignozlogsnormalizerRecords metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizerRecordsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizerRecords, obs: o})
		return nil
	}, builder.SignozlogsnormalizerRecords)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.SignozlogsnormalizerFieldInferences, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.field.inferences",
		metric.WithDescription("Top level fields inferred, by target, the field read and where it was found. [Alpha]"),
		metric.WithUnit("{field}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizerMessageFlattenings, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.message.flattenings",
		metric.WithDescription("Object messages lifted to the top level of the body. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizerMessageNestedPromotions, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.message.nested_promotions",
		metric.WithDescription("Flattened messages whose own message field became the message. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizerMessagePromotions, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.message.promotions",
		metric.WithDescription("Messages promoted from a configured message field, by field. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizerMessageStringifications, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.message.stringifications",
		metric.WithDescription("Messages neither text nor an object, stringified on storage by the typed body_v2.message path. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizerRecords, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalizer.records",
		metric.WithDescription("Log records normalized, by body type. [Alpha]"),
		metric.WithUnit("{record}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
