// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"time"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/collector/filter"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver"
)

var MetricsInfo = metricsInfo{
	ClickhouseViewRefreshException: metricInfo{
		Name: "clickhouse.view_refresh.exception",
	},
	ClickhouseViewRefreshLastDuration: metricInfo{
		Name: "clickhouse.view_refresh.last_duration",
	},
	ClickhouseViewRefreshLastSuccessAge: metricInfo{
		Name: "clickhouse.view_refresh.last_success_age",
	},
	ClickhouseViewRefreshProgress: metricInfo{
		Name: "clickhouse.view_refresh.progress",
	},
	ClickhouseViewRefreshRetry: metricInfo{
		Name: "clickhouse.view_refresh.retry",
	},
}

type metricsInfo struct {
	ClickhouseViewRefreshException      metricInfo
	ClickhouseViewRefreshLastDuration   metricInfo
	ClickhouseViewRefreshLastSuccessAge metricInfo
	ClickhouseViewRefreshProgress       metricInfo
	ClickhouseViewRefreshRetry          metricInfo
}

type metricInfo struct {
	Name string
}

type metricClickhouseViewRefreshException struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills clickhouse.view_refresh.exception metric with initial data.
func (m *metricClickhouseViewRefreshException) init() {
	m.data.SetName("clickhouse.view_refresh.exception")
	m.data.SetDescription("1 if the view's last refresh ended in an exception, 0 otherwise.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricClickhouseViewRefreshException) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("database", databaseAttributeValue)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricClickhouseViewRefreshException) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricClickhouseViewRefreshException) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricClickhouseViewRefreshException(cfg MetricConfig) metricClickhouseViewRefreshException {
	m := metricClickhouseViewRefreshException{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricClickhouseViewRefreshLastDuration struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills clickhouse.view_refresh.last_duration metric with initial data.
func (m *metricClickhouseViewRefreshLastDuration) init() {
	m.data.SetName("clickhouse.view_refresh.last_duration")
	m.data.SetDescription("Duration of the most recent refresh of the view. Compared against the refresh cadence to detect overrun.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricClickhouseViewRefreshLastDuration) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, databaseAttributeValue string, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("database", databaseAttributeValue)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricClickhouseViewRefreshLastDuration) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricClickhouseViewRefreshLastDuration) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricClickhouseViewRefreshLastDuration(cfg MetricConfig) metricClickhouseViewRefreshLastDuration {
	m := metricClickhouseViewRefreshLastDuration{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricClickhouseViewRefreshLastSuccessAge struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills clickhouse.view_refresh.last_success_age metric with initial data.
func (m *metricClickhouseViewRefreshLastSuccessAge) init() {
	m.data.SetName("clickhouse.view_refresh.last_success_age")
	m.data.SetDescription("Seconds since the last successful refresh of the view (now() - last_success_time). Primary staleness signal for refreshable materialized views.")
	m.data.SetUnit("s")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricClickhouseViewRefreshLastSuccessAge) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("database", databaseAttributeValue)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricClickhouseViewRefreshLastSuccessAge) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricClickhouseViewRefreshLastSuccessAge) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricClickhouseViewRefreshLastSuccessAge(cfg MetricConfig) metricClickhouseViewRefreshLastSuccessAge {
	m := metricClickhouseViewRefreshLastSuccessAge{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricClickhouseViewRefreshProgress struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills clickhouse.view_refresh.progress metric with initial data.
func (m *metricClickhouseViewRefreshProgress) init() {
	m.data.SetName("clickhouse.view_refresh.progress")
	m.data.SetDescription("Progress of an in-flight refresh, between 0 and 1.")
	m.data.SetUnit("1")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricClickhouseViewRefreshProgress) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val float64, databaseAttributeValue string, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetDoubleValue(val)
	dp.Attributes().PutStr("database", databaseAttributeValue)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricClickhouseViewRefreshProgress) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricClickhouseViewRefreshProgress) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricClickhouseViewRefreshProgress(cfg MetricConfig) metricClickhouseViewRefreshProgress {
	m := metricClickhouseViewRefreshProgress{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

type metricClickhouseViewRefreshRetry struct {
	data     pmetric.Metric // data buffer for generated metric.
	config   MetricConfig   // metric config provided by user.
	capacity int            // max observed number of data points added to the metric.
}

// init fills clickhouse.view_refresh.retry metric with initial data.
func (m *metricClickhouseViewRefreshRetry) init() {
	m.data.SetName("clickhouse.view_refresh.retry")
	m.data.SetDescription("Current retry count for the view's refresh.")
	m.data.SetUnit("{retries}")
	m.data.SetEmptyGauge()
	m.data.Gauge().DataPoints().EnsureCapacity(m.capacity)
}

func (m *metricClickhouseViewRefreshRetry) recordDataPoint(start pcommon.Timestamp, ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	if !m.config.Enabled {
		return
	}
	dp := m.data.Gauge().DataPoints().AppendEmpty()
	dp.SetStartTimestamp(start)
	dp.SetTimestamp(ts)
	dp.SetIntValue(val)
	dp.Attributes().PutStr("database", databaseAttributeValue)
	dp.Attributes().PutStr("view", viewAttributeValue)
}

// updateCapacity saves max length of data point slices that will be used for the slice capacity.
func (m *metricClickhouseViewRefreshRetry) updateCapacity() {
	if m.data.Gauge().DataPoints().Len() > m.capacity {
		m.capacity = m.data.Gauge().DataPoints().Len()
	}
}

// emit appends recorded metric data to a metrics slice and prepares it for recording another set of data points.
func (m *metricClickhouseViewRefreshRetry) emit(metrics pmetric.MetricSlice) {
	if m.config.Enabled && m.data.Gauge().DataPoints().Len() > 0 {
		m.updateCapacity()
		m.data.MoveTo(metrics.AppendEmpty())
		m.init()
	}
}

func newMetricClickhouseViewRefreshRetry(cfg MetricConfig) metricClickhouseViewRefreshRetry {
	m := metricClickhouseViewRefreshRetry{config: cfg}
	if cfg.Enabled {
		m.data = pmetric.NewMetric()
		m.init()
	}
	return m
}

// MetricsBuilder provides an interface for scrapers to report metrics while taking care of all the transformations
// required to produce metric representation defined in metadata and user config.
type MetricsBuilder struct {
	config                                    MetricsBuilderConfig // config of the metrics builder.
	startTime                                 pcommon.Timestamp    // start time that will be applied to all recorded data points.
	metricsCapacity                           int                  // maximum observed number of metrics per resource.
	metricsBuffer                             pmetric.Metrics      // accumulates metrics data before emitting.
	buildInfo                                 component.BuildInfo  // contains version information.
	resourceAttributeIncludeFilter            map[string]filter.Filter
	resourceAttributeExcludeFilter            map[string]filter.Filter
	metricClickhouseViewRefreshException      metricClickhouseViewRefreshException
	metricClickhouseViewRefreshLastDuration   metricClickhouseViewRefreshLastDuration
	metricClickhouseViewRefreshLastSuccessAge metricClickhouseViewRefreshLastSuccessAge
	metricClickhouseViewRefreshProgress       metricClickhouseViewRefreshProgress
	metricClickhouseViewRefreshRetry          metricClickhouseViewRefreshRetry
}

// MetricBuilderOption applies changes to default metrics builder.
type MetricBuilderOption interface {
	apply(*MetricsBuilder)
}

type metricBuilderOptionFunc func(mb *MetricsBuilder)

func (mbof metricBuilderOptionFunc) apply(mb *MetricsBuilder) {
	mbof(mb)
}

// WithStartTime sets startTime on the metrics builder.
func WithStartTime(startTime pcommon.Timestamp) MetricBuilderOption {
	return metricBuilderOptionFunc(func(mb *MetricsBuilder) {
		mb.startTime = startTime
	})
}
func NewMetricsBuilder(mbc MetricsBuilderConfig, settings receiver.Settings, options ...MetricBuilderOption) *MetricsBuilder {
	mb := &MetricsBuilder{
		config:                                  mbc,
		startTime:                               pcommon.NewTimestampFromTime(time.Now()),
		metricsBuffer:                           pmetric.NewMetrics(),
		buildInfo:                               settings.BuildInfo,
		metricClickhouseViewRefreshException:    newMetricClickhouseViewRefreshException(mbc.Metrics.ClickhouseViewRefreshException),
		metricClickhouseViewRefreshLastDuration: newMetricClickhouseViewRefreshLastDuration(mbc.Metrics.ClickhouseViewRefreshLastDuration),
		metricClickhouseViewRefreshLastSuccessAge: newMetricClickhouseViewRefreshLastSuccessAge(mbc.Metrics.ClickhouseViewRefreshLastSuccessAge),
		metricClickhouseViewRefreshProgress:       newMetricClickhouseViewRefreshProgress(mbc.Metrics.ClickhouseViewRefreshProgress),
		metricClickhouseViewRefreshRetry:          newMetricClickhouseViewRefreshRetry(mbc.Metrics.ClickhouseViewRefreshRetry),
		resourceAttributeIncludeFilter:            make(map[string]filter.Filter),
		resourceAttributeExcludeFilter:            make(map[string]filter.Filter),
	}
	if mbc.ResourceAttributes.ClickhouseHostname.MetricsInclude != nil {
		mb.resourceAttributeIncludeFilter["clickhouse.hostname"] = filter.CreateFilter(mbc.ResourceAttributes.ClickhouseHostname.MetricsInclude)
	}
	if mbc.ResourceAttributes.ClickhouseHostname.MetricsExclude != nil {
		mb.resourceAttributeExcludeFilter["clickhouse.hostname"] = filter.CreateFilter(mbc.ResourceAttributes.ClickhouseHostname.MetricsExclude)
	}

	for _, op := range options {
		op.apply(mb)
	}
	return mb
}

// NewResourceBuilder returns a new resource builder that should be used to build a resource associated with for the emitted metrics.
func (mb *MetricsBuilder) NewResourceBuilder() *ResourceBuilder {
	return NewResourceBuilder(mb.config.ResourceAttributes)
}

// updateCapacity updates max length of metrics and resource attributes that will be used for the slice capacity.
func (mb *MetricsBuilder) updateCapacity(rm pmetric.ResourceMetrics) {
	if mb.metricsCapacity < rm.ScopeMetrics().At(0).Metrics().Len() {
		mb.metricsCapacity = rm.ScopeMetrics().At(0).Metrics().Len()
	}
}

// ResourceMetricsOption applies changes to provided resource metrics.
type ResourceMetricsOption interface {
	apply(pmetric.ResourceMetrics)
}

type resourceMetricsOptionFunc func(pmetric.ResourceMetrics)

func (rmof resourceMetricsOptionFunc) apply(rm pmetric.ResourceMetrics) {
	rmof(rm)
}

// WithResource sets the provided resource on the emitted ResourceMetrics.
// It's recommended to use ResourceBuilder to create the resource.
func WithResource(res pcommon.Resource) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		res.CopyTo(rm.Resource())
	})
}

// WithStartTimeOverride overrides start time for all the resource metrics data points.
// This option should be only used if different start time has to be set on metrics coming from different resources.
func WithStartTimeOverride(start pcommon.Timestamp) ResourceMetricsOption {
	return resourceMetricsOptionFunc(func(rm pmetric.ResourceMetrics) {
		var dps pmetric.NumberDataPointSlice
		metrics := rm.ScopeMetrics().At(0).Metrics()
		for i := 0; i < metrics.Len(); i++ {
			switch metrics.At(i).Type() {
			case pmetric.MetricTypeGauge:
				dps = metrics.At(i).Gauge().DataPoints()
			case pmetric.MetricTypeSum:
				dps = metrics.At(i).Sum().DataPoints()
			}
			for j := 0; j < dps.Len(); j++ {
				dps.At(j).SetStartTimestamp(start)
			}
		}
	})
}

// EmitForResource saves all the generated metrics under a new resource and updates the internal state to be ready for
// recording another set of data points as part of another resource. This function can be helpful when one scraper
// needs to emit metrics from several resources. Otherwise calling this function is not required,
// just `Emit` function can be called instead.
// Resource attributes should be provided as ResourceMetricsOption arguments.
func (mb *MetricsBuilder) EmitForResource(options ...ResourceMetricsOption) {
	rm := pmetric.NewResourceMetrics()
	ils := rm.ScopeMetrics().AppendEmpty()
	ils.Scope().SetName(ScopeName)
	ils.Scope().SetVersion(mb.buildInfo.Version)
	ils.Metrics().EnsureCapacity(mb.metricsCapacity)
	mb.metricClickhouseViewRefreshException.emit(ils.Metrics())
	mb.metricClickhouseViewRefreshLastDuration.emit(ils.Metrics())
	mb.metricClickhouseViewRefreshLastSuccessAge.emit(ils.Metrics())
	mb.metricClickhouseViewRefreshProgress.emit(ils.Metrics())
	mb.metricClickhouseViewRefreshRetry.emit(ils.Metrics())

	for _, op := range options {
		op.apply(rm)
	}
	for attr, filter := range mb.resourceAttributeIncludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && !filter.Matches(val.AsString()) {
			return
		}
	}
	for attr, filter := range mb.resourceAttributeExcludeFilter {
		if val, ok := rm.Resource().Attributes().Get(attr); ok && filter.Matches(val.AsString()) {
			return
		}
	}

	if ils.Metrics().Len() > 0 {
		mb.updateCapacity(rm)
		rm.MoveTo(mb.metricsBuffer.ResourceMetrics().AppendEmpty())
	}
}

// Emit returns all the metrics accumulated by the metrics builder and updates the internal state to be ready for
// recording another set of metrics. This function will be responsible for applying all the transformations required to
// produce metric representation defined in metadata and user config, e.g. delta or cumulative.
func (mb *MetricsBuilder) Emit(options ...ResourceMetricsOption) pmetric.Metrics {
	mb.EmitForResource(options...)
	metrics := mb.metricsBuffer
	mb.metricsBuffer = pmetric.NewMetrics()
	return metrics
}

// RecordClickhouseViewRefreshExceptionDataPoint adds a data point to clickhouse.view_refresh.exception metric.
func (mb *MetricsBuilder) RecordClickhouseViewRefreshExceptionDataPoint(ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	mb.metricClickhouseViewRefreshException.recordDataPoint(mb.startTime, ts, val, databaseAttributeValue, viewAttributeValue)
}

// RecordClickhouseViewRefreshLastDurationDataPoint adds a data point to clickhouse.view_refresh.last_duration metric.
func (mb *MetricsBuilder) RecordClickhouseViewRefreshLastDurationDataPoint(ts pcommon.Timestamp, val float64, databaseAttributeValue string, viewAttributeValue string) {
	mb.metricClickhouseViewRefreshLastDuration.recordDataPoint(mb.startTime, ts, val, databaseAttributeValue, viewAttributeValue)
}

// RecordClickhouseViewRefreshLastSuccessAgeDataPoint adds a data point to clickhouse.view_refresh.last_success_age metric.
func (mb *MetricsBuilder) RecordClickhouseViewRefreshLastSuccessAgeDataPoint(ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	mb.metricClickhouseViewRefreshLastSuccessAge.recordDataPoint(mb.startTime, ts, val, databaseAttributeValue, viewAttributeValue)
}

// RecordClickhouseViewRefreshProgressDataPoint adds a data point to clickhouse.view_refresh.progress metric.
func (mb *MetricsBuilder) RecordClickhouseViewRefreshProgressDataPoint(ts pcommon.Timestamp, val float64, databaseAttributeValue string, viewAttributeValue string) {
	mb.metricClickhouseViewRefreshProgress.recordDataPoint(mb.startTime, ts, val, databaseAttributeValue, viewAttributeValue)
}

// RecordClickhouseViewRefreshRetryDataPoint adds a data point to clickhouse.view_refresh.retry metric.
func (mb *MetricsBuilder) RecordClickhouseViewRefreshRetryDataPoint(ts pcommon.Timestamp, val int64, databaseAttributeValue string, viewAttributeValue string) {
	mb.metricClickhouseViewRefreshRetry.recordDataPoint(mb.startTime, ts, val, databaseAttributeValue, viewAttributeValue)
}

// Reset resets metrics builder to its initial state. It should be used when external metrics source is restarted,
// and metrics builder should update its startTime and reset it's internal state accordingly.
func (mb *MetricsBuilder) Reset(options ...MetricBuilderOption) {
	mb.startTime = pcommon.NewTimestampFromTime(time.Now())
	for _, op := range options {
		op.apply(mb)
	}
}
