// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("clickhousesystemtablesreceiver")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/receiver/clickhousesystemtablesreceiver"
)

const (
	LogsStability = component.StabilityLevelBeta
)
