// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"testing"

	"github.com/stretchr/testify/assert"
	"go.opentelemetry.io/collector/pdata/pcommon"
	"go.opentelemetry.io/collector/pdata/pmetric"
	"go.opentelemetry.io/collector/receiver/receivertest"
	"go.uber.org/zap"
	"go.uber.org/zap/zaptest/observer"
)

type testDataSet int

const (
	testDataSetDefault testDataSet = iota
	testDataSetAll
	testDataSetNone
)

func TestMetricsBuilder(t *testing.T) {
	tests := []struct {
		name        string
		metricsSet  testDataSet
		resAttrsSet testDataSet
		expectEmpty bool
	}{
		{
			name: "default",
		},
		{
			name:        "all_set",
			metricsSet:  testDataSetAll,
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "none_set",
			metricsSet:  testDataSetNone,
			resAttrsSet: testDataSetNone,
			expectEmpty: true,
		},
		{
			name:        "filter_set_include",
			resAttrsSet: testDataSetAll,
		},
		{
			name:        "filter_set_exclude",
			resAttrsSet: testDataSetAll,
			expectEmpty: true,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			start := pcommon.Timestamp(1_000_000_000)
			ts := pcommon.Timestamp(1_000_001_000)
			observedZapCore, observedLogs := observer.New(zap.WarnLevel)
			settings := receivertest.NewNopSettings(receivertest.NopType)
			settings.Logger = zap.New(observedZapCore)
			mb := NewMetricsBuilder(loadMetricsBuilderConfig(t, tt.name), settings, WithStartTime(start))

			expectedWarnings := 0

			assert.Equal(t, expectedWarnings, observedLogs.Len())

			defaultMetricsCount := 0
			allMetricsCount := 0

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordClickhouseViewRefreshExceptionDataPoint(ts, 1, "database-val", "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordClickhouseViewRefreshLastDurationDataPoint(ts, 1, "database-val", "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordClickhouseViewRefreshLastSuccessAgeDataPoint(ts, 1, "database-val", "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordClickhouseViewRefreshProgressDataPoint(ts, 1, "database-val", "view-val")

			defaultMetricsCount++
			allMetricsCount++
			mb.RecordClickhouseViewRefreshRetryDataPoint(ts, 1, "database-val", "view-val")

			rb := mb.NewResourceBuilder()
			rb.SetClickhouseHostname("clickhouse.hostname-val")
			res := rb.Emit()
			metrics := mb.Emit(WithResource(res))

			if tt.expectEmpty {
				assert.Equal(t, 0, metrics.ResourceMetrics().Len())
				return
			}

			assert.Equal(t, 1, metrics.ResourceMetrics().Len())
			rm := metrics.ResourceMetrics().At(0)
			assert.Equal(t, res, rm.Resource())
			assert.Equal(t, 1, rm.ScopeMetrics().Len())
			ms := rm.ScopeMetrics().At(0).Metrics()
			if tt.metricsSet == testDataSetDefault {
				assert.Equal(t, defaultMetricsCount, ms.Len())
			}
			if tt.metricsSet == testDataSetAll {
				assert.Equal(t, allMetricsCount, ms.Len())
			}
			validatedMetrics := make(map[string]bool)
			for i := 0; i < ms.Len(); i++ {
				switch ms.At(i).Name() {
				case "clickhouse.view_refresh.exception":
					assert.False(t, validatedMetrics["clickhouse.view_refresh.exception"], "Found a duplicate in the metrics slice: clickhouse.view_refresh.exception")
					validatedMetrics["clickhouse.view_refresh.exception"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "1 if the view's last refresh ended in an exception, 0 otherwise.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", attrVal.Str())
				case "clickhouse.view_refresh.last_duration":
					assert.False(t, validatedMetrics["clickhouse.view_refresh.last_duration"], "Found a duplicate in the metrics slice: clickhouse.view_refresh.last_duration")
					validatedMetrics["clickhouse.view_refresh.last_duration"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Duration of the most recent refresh of the view. Compared against the refresh cadence to detect overrun.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", attrVal.Str())
				case "clickhouse.view_refresh.last_success_age":
					assert.False(t, validatedMetrics["clickhouse.view_refresh.last_success_age"], "Found a duplicate in the metrics slice: clickhouse.view_refresh.last_success_age")
					validatedMetrics["clickhouse.view_refresh.last_success_age"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Seconds since the last successful refresh of the view (now() - last_success_time). Primary staleness signal for refreshable materialized views.", ms.At(i).Description())
					assert.Equal(t, "s", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", attrVal.Str())
				case "clickhouse.view_refresh.progress":
					assert.False(t, validatedMetrics["clickhouse.view_refresh.progress"], "Found a duplicate in the metrics slice: clickhouse.view_refresh.progress")
					validatedMetrics["clickhouse.view_refresh.progress"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Progress of an in-flight refresh, between 0 and 1.", ms.At(i).Description())
					assert.Equal(t, "1", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeDouble, dp.ValueType())
					assert.InDelta(t, float64(1), dp.DoubleValue(), 0.01)
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", attrVal.Str())
				case "clickhouse.view_refresh.retry":
					assert.False(t, validatedMetrics["clickhouse.view_refresh.retry"], "Found a duplicate in the metrics slice: clickhouse.view_refresh.retry")
					validatedMetrics["clickhouse.view_refresh.retry"] = true
					assert.Equal(t, pmetric.MetricTypeGauge, ms.At(i).Type())
					assert.Equal(t, 1, ms.At(i).Gauge().DataPoints().Len())
					assert.Equal(t, "Current retry count for the view's refresh.", ms.At(i).Description())
					assert.Equal(t, "{retries}", ms.At(i).Unit())
					dp := ms.At(i).Gauge().DataPoints().At(0)
					assert.Equal(t, start, dp.StartTimestamp())
					assert.Equal(t, ts, dp.Timestamp())
					assert.Equal(t, pmetric.NumberDataPointValueTypeInt, dp.ValueType())
					assert.Equal(t, int64(1), dp.IntValue())
					attrVal, ok := dp.Attributes().Get("database")
					assert.True(t, ok)
					assert.Equal(t, "database-val", attrVal.Str())
					attrVal, ok = dp.Attributes().Get("view")
					assert.True(t, ok)
					assert.Equal(t, "view-val", attrVal.Str())
				}
			}
		})
	}
}
