// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/SigNoz/signoz-otel-collector/connectors/signozmeterconnector")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/SigNoz/signoz-otel-collector/connectors/signozmeterconnector")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                              metric.Meter
	mu                                                 sync.Mutex
	registrations                                      []metric.Registration
	ConnectorProducedItemsFailedCount                  metric.Int64Counter
	ConnectorProducedItemsSentCount                    metric.Int64Counter
	ConnectorReceivedAcceptedItemsLogCount             metric.Int64Counter
	ConnectorReceivedAcceptedItemsMetricDatapointCount metric.Int64Counter
	ConnectorReceivedAcceptedItemsSpanCount            metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.ConnectorProducedItemsFailedCount, err = builder.meter.Int64Counter(
		"otelcol_connector.produced.items.failed.count",
		metric.WithDescription("Number of datapoints failed to be exported from connector"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorProducedItemsSentCount, err = builder.meter.Int64Counter(
		"otelcol_connector.produced.items.sent.count",
		metric.WithDescription("Number of datapoints successfully exported from connector"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorReceivedAcceptedItemsLogCount, err = builder.meter.Int64Counter(
		"otelcol_connector.received.accepted.items.log.count",
		metric.WithDescription("Number of log records successfully received  from the upstream pipeline"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorReceivedAcceptedItemsMetricDatapointCount, err = builder.meter.Int64Counter(
		"otelcol_connector.received.accepted.items.metric.datapoint.count",
		metric.WithDescription("Number of metric datapoints successfully received from the upstream pipeline"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	builder.ConnectorReceivedAcceptedItemsSpanCount, err = builder.meter.Int64Counter(
		"otelcol_connector.received.accepted.items.span.count",
		metric.WithDescription("Number of spans successfully received from the upstream pipeline"),
		metric.WithUnit("1"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
