// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozllmpricing")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/processor/signozllmpricingprocessor"
)

const (
	TracesStability = component.StabilityLevelDevelopment
)
