// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/SigNoz/signoz-otel-collector/processor/signozlogsinferrerprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/SigNoz/signoz-otel-collector/processor/signozlogsinferrerprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                             metric.Meter
	mu                                sync.Mutex
	registrations                     []metric.Registration
	SignozlogsinferrerFieldInferences metric.Int64ObservableCounter
	SignozlogsinferrerLogRecords      metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterSignozlogsinferrerFieldInferencesCallback sets callback for observable SignozlogsinferrerFieldInferences metric.
func (builder *TelemetryBuilder) RegisterSignozlogsinferrerFieldInferencesCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsinferrerFieldInferences, obs: o})
		return nil
	}, builder.SignozlogsinferrerFieldInferences)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsinferrerLogRecordsCallback sets callback for observable SignozlogsinferrerLogRecords metric.
func (builder *TelemetryBuilder) RegisterSignozlogsinferrerLogRecordsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsinferrerLogRecords, obs: o})
		return nil
	}, builder.SignozlogsinferrerLogRecords)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.SignozlogsinferrerFieldInferences, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsinferrer.field.inferences",
		metric.WithDescription("Top level fields inferred, by target, the field read and where it was found. [Alpha]"),
		metric.WithUnit("{field}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsinferrerLogRecords, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsinferrer.log.records",
		metric.WithDescription("Log records processed. [Alpha]"),
		metric.WithUnit("{record}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
