// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozkafkareceiver")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/receiver/signozkafkareceiver"
)

const (
	MetricsStability = component.StabilityLevelBeta
	LogsStability    = component.StabilityLevelBeta
	TracesStability  = component.StabilityLevelBeta
)
