// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozclickhousemetrics")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/exporter/signozclickhousemetrics"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
