// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozspanmetrics")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/connectors/signozspanmetricsconnector"
)

const (
	TracesToMetricsStability = component.StabilityLevelAlpha
)
