// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("signozclickhousemeter")
	ScopeName = "github.com/SigNoz/signoz-otel-collector/exporter/signozclickhousemeter"
)

const (
	MetricsStability = component.StabilityLevelBeta
)
