// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/SigNoz/signoz-otel-collector/pkg/timebucketedset")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/SigNoz/signoz-otel-collector/pkg/timebucketedset")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                          metric.Meter
	mu                             sync.Mutex
	registrations                  []metric.Registration
	TimebucketedsetApplyIds        metric.Int64ObservableCounter
	TimebucketedsetBucketCount     metric.Int64ObservableUpDownCounter
	TimebucketedsetBucketEvictions metric.Int64ObservableCounter
	TimebucketedsetIDCount         metric.Int64ObservableUpDownCounter
	TimebucketedsetMemoryLimit     metric.Int64ObservableUpDownCounter
	TimebucketedsetMemoryUsage     metric.Int64ObservableUpDownCounter
	TimebucketedsetPlanIds         metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterTimebucketedsetApplyIdsCallback sets callback for observable TimebucketedsetApplyIds metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetApplyIdsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetApplyIds, obs: o})
		return nil
	}, builder.TimebucketedsetApplyIds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetBucketCountCallback sets callback for observable TimebucketedsetBucketCount metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetBucketCountCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetBucketCount, obs: o})
		return nil
	}, builder.TimebucketedsetBucketCount)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetBucketEvictionsCallback sets callback for observable TimebucketedsetBucketEvictions metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetBucketEvictionsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetBucketEvictions, obs: o})
		return nil
	}, builder.TimebucketedsetBucketEvictions)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetIDCountCallback sets callback for observable TimebucketedsetIDCount metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetIDCountCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetIDCount, obs: o})
		return nil
	}, builder.TimebucketedsetIDCount)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetMemoryLimitCallback sets callback for observable TimebucketedsetMemoryLimit metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetMemoryLimitCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetMemoryLimit, obs: o})
		return nil
	}, builder.TimebucketedsetMemoryLimit)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetMemoryUsageCallback sets callback for observable TimebucketedsetMemoryUsage metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetMemoryUsageCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetMemoryUsage, obs: o})
		return nil
	}, builder.TimebucketedsetMemoryUsage)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterTimebucketedsetPlanIdsCallback sets callback for observable TimebucketedsetPlanIds metric.
func (builder *TelemetryBuilder) RegisterTimebucketedsetPlanIdsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.TimebucketedsetPlanIds, obs: o})
		return nil
	}, builder.TimebucketedsetPlanIds)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.TimebucketedsetApplyIds, err = builder.meter.Int64ObservableCounter(
		"otelcol.timebucketedset.apply.ids",
		metric.WithDescription("Ids given to Apply. An ignored id belongs to a bucket that is no longer live; its next Plan is a miss again. [Alpha]"),
		metric.WithUnit("{id}"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetBucketCount, err = builder.meter.Int64ObservableUpDownCounter(
		"otelcol.timebucketedset.bucket.count",
		metric.WithDescription("Live buckets. [Alpha]"),
		metric.WithUnit("{bucket}"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetBucketEvictions, err = builder.meter.Int64ObservableCounter(
		"otelcol.timebucketedset.bucket.evictions",
		metric.WithDescription("Buckets evicted to make room for a newer bucket. [Alpha]"),
		metric.WithUnit("{bucket}"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetIDCount, err = builder.meter.Int64ObservableUpDownCounter(
		"otelcol.timebucketedset.id.count",
		metric.WithDescription("Entries across live buckets, one per bucket an id is registered in. [Alpha]"),
		metric.WithUnit("{id}"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetMemoryLimit, err = builder.meter.Int64ObservableUpDownCounter(
		"otelcol.timebucketedset.memory.limit",
		metric.WithDescription("Chunk capacity of live buckets. Once a fastcache shard has filled its chunks it overwrites its oldest ids. [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetMemoryUsage, err = builder.meter.Int64ObservableUpDownCounter(
		"otelcol.timebucketedset.memory.usage",
		metric.WithDescription("Bytes of fastcache chunks allocated by live buckets. [Alpha]"),
		metric.WithUnit("By"),
	)
	errs = errors.Join(errs, err)
	builder.TimebucketedsetPlanIds, err = builder.meter.Int64ObservableCounter(
		"otelcol.timebucketedset.plan.ids",
		metric.WithDescription("Ids given to Plan, by answer. miss: write. hit: skip. pre_write: skip, but write to the next bucket. no_bucket: write, nothing is cached. [Alpha]"),
		metric.WithUnit("{id}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
