// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"context"
	"errors"
	"sync"

	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/metric/embedded"
	"go.opentelemetry.io/otel/trace"

	"go.opentelemetry.io/collector/component"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/SigNoz/signoz-otel-collector/processor/signozlogsnormalizeprocessor")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/SigNoz/signoz-otel-collector/processor/signozlogsnormalizeprocessor")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                                      metric.Meter
	mu                                         sync.Mutex
	registrations                              []metric.Registration
	SignozlogsnormalizeMessageFlattenings      metric.Int64ObservableCounter
	SignozlogsnormalizeMessageNestedPromotions metric.Int64ObservableCounter
	SignozlogsnormalizeMessagePromotions       metric.Int64ObservableCounter
	SignozlogsnormalizeMessageStringifications metric.Int64ObservableCounter
	SignozlogsnormalizeRecords                 metric.Int64ObservableCounter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// RegisterSignozlogsnormalizeMessageFlatteningsCallback sets callback for observable SignozlogsnormalizeMessageFlattenings metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizeMessageFlatteningsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizeMessageFlattenings, obs: o})
		return nil
	}, builder.SignozlogsnormalizeMessageFlattenings)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizeMessageNestedPromotionsCallback sets callback for observable SignozlogsnormalizeMessageNestedPromotions metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizeMessageNestedPromotionsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizeMessageNestedPromotions, obs: o})
		return nil
	}, builder.SignozlogsnormalizeMessageNestedPromotions)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizeMessagePromotionsCallback sets callback for observable SignozlogsnormalizeMessagePromotions metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizeMessagePromotionsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizeMessagePromotions, obs: o})
		return nil
	}, builder.SignozlogsnormalizeMessagePromotions)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizeMessageStringificationsCallback sets callback for observable SignozlogsnormalizeMessageStringifications metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizeMessageStringificationsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizeMessageStringifications, obs: o})
		return nil
	}, builder.SignozlogsnormalizeMessageStringifications)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

// RegisterSignozlogsnormalizeRecordsCallback sets callback for observable SignozlogsnormalizeRecords metric.
func (builder *TelemetryBuilder) RegisterSignozlogsnormalizeRecordsCallback(cb metric.Int64Callback) error {
	reg, err := builder.meter.RegisterCallback(func(ctx context.Context, o metric.Observer) error {
		cb(ctx, &observerInt64{inst: builder.SignozlogsnormalizeRecords, obs: o})
		return nil
	}, builder.SignozlogsnormalizeRecords)
	if err != nil {
		return err
	}
	builder.mu.Lock()
	defer builder.mu.Unlock()
	builder.registrations = append(builder.registrations, reg)
	return nil
}

type observerInt64 struct {
	embedded.Int64Observer
	inst metric.Int64Observable
	obs  metric.Observer
}

func (oi *observerInt64) Observe(value int64, opts ...metric.ObserveOption) {
	oi.obs.ObserveInt64(oi.inst, value, opts...)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.SignozlogsnormalizeMessageFlattenings, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalize.message.flattenings",
		metric.WithDescription("Object messages lifted to the top level of the body. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizeMessageNestedPromotions, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalize.message.nested_promotions",
		metric.WithDescription("Flattened messages whose own message field became the message. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizeMessagePromotions, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalize.message.promotions",
		metric.WithDescription("Messages promoted from a configured message field, by field. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizeMessageStringifications, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalize.message.stringifications",
		metric.WithDescription("Messages neither text nor an object, stringified on storage by the typed body_v2.message path. [Alpha]"),
		metric.WithUnit("{message}"),
	)
	errs = errors.Join(errs, err)
	builder.SignozlogsnormalizeRecords, err = builder.meter.Int64ObservableCounter(
		"otelcol.signozlogsnormalize.records",
		metric.WithDescription("Log records normalized, by body type. [Alpha]"),
		metric.WithUnit("{record}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
