name: Push

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  image-build-and-push-signoz-collector:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker-qemu
        uses: docker/setup-qemu-action@v2
      - name: docker-buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: github-ref-info
        shell: bash
        run: |
          GH_REF=${{ github.ref }}
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            PREFIX="refs/tags/"
            echo "GH_IS_TAG=true" >> $GITHUB_ENV
            echo "GH_TAG=${GH_REF#$PREFIX}" >> $GITHUB_ENV
          else
            PREFIX="refs/heads/"
            echo "GH_IS_TAG=false" >> $GITHUB_ENV
            echo "GH_BRANCH_NAME=${GH_REF#$PREFIX}" >> $GITHUB_ENV
          fi
      - name: set-docker-tag-env
        run: |
          if [ '${{ env.GH_IS_TAG }}' == 'true' ]; then
            echo "DOCKER_TAG=${{ env.GH_TAG }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ env.GH_BRANCH_NAME }}" >> $GITHUB_ENV
          fi
      - name: build-artifacts
        run: make build-all
      - name: build-and-push-docker-image
        run: make build-and-push-signoz-collector
      - name: set-docker-tag-env-without-v-prefix
        if: env.GH_IS_TAG == 'true'
        run: |
          tag="${{ env.GH_TAG }}"
          tag="${tag:1}"
          echo "DOCKER_TAG=$tag" >> $GITHUB_ENV
      - name: build-and-push-docker-image-without-v-prefix
        if: env.GH_IS_TAG == 'true'
        run: make build-and-push-signoz-collector
  image-build-and-push-schema-migrator:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: docker-qemu
        uses: docker/setup-qemu-action@v2
      - name: docker-buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: github-ref-info
        shell: bash
        run: |
          GH_REF=${{ github.ref }}
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            PREFIX="refs/tags/"
            echo "GH_IS_TAG=true" >> $GITHUB_ENV
            echo "GH_TAG=${GH_REF#$PREFIX}" >> $GITHUB_ENV
          else
            PREFIX="refs/heads/"
            echo "GH_IS_TAG=false" >> $GITHUB_ENV
            echo "GH_BRANCH_NAME=${GH_REF#$PREFIX}" >> $GITHUB_ENV
          fi
      - name: build-artifacts
        run: make build-all
      - name: set-docker-tag-env
        shell: bash
        run: |
          if [[ "${{ env.GH_IS_TAG }}" == "true" ]]; then
            echo "DOCKER_TAG=${{ env.GH_TAG }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ env.GH_BRANCH_NAME }}" >> $GITHUB_ENV
          fi
      - name: build-and-push-docker-image
        run: make build-and-push-signoz-schema-migrator
      - name: set-docker-tag-env-without-v-prefix
        if: env.GH_IS_TAG == 'true'
        run: |
          tag="${{ env.GH_TAG }}"
          tag="${tag:1}"
          echo "DOCKER_TAG=$tag" >> $GITHUB_ENV
      - name: build-and-push-docker-image-without-v-prefix
        if: env.GH_IS_TAG == 'true'
        run: make build-and-push-signoz-schema-migrator
