name: Push

on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*

jobs:
  image-build-and-push-signoz-collector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7
      - name: Set docker tag environment
        run: |
          if [ '${{ steps.branch-name.outputs.is_tag }}' == 'true' ]; then
            echo "DOCKER_TAG=${{ steps.branch-name.outputs.tag }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
          fi
      - name: Build artifacts for arm64/amd64
        run: make build-all
      - name: Build and push docker image
        run: make build-and-push-signoz-collector
      - name: Set docker tag environment without v prefix
        run: |
          if [ '${{ steps.branch-name.outputs.is_tag }}' == 'true' ]; then
            tag="${{ steps.branch-name.outputs.tag }}"
            tag="${tag:1}"
            echo "DOCKER_TAG=$tag" >> $GITHUB_ENV
          fi
      - name: Build artifacts for arm64/amd64
        run: make build-all
      - name: Build and push docker image without v prefix
        run: make build-and-push-signoz-collector
  image-build-and-push-schema-migrator:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: benjlevesque/short-sha@v2.2
        id: short-sha
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7.0.7
      - name: Set docker tag environment
        run: |
          if [ '${{ steps.branch-name.outputs.is_tag }}' == 'true' ]; then
            echo "DOCKER_TAG=${{ steps.branch-name.outputs.tag }}" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG=${{ steps.branch-name.outputs.current_branch }}" >> $GITHUB_ENV
          fi
      - name: Build artifacts for arm64/amd64
        run: make build-all
      - name: Build and push docker image
        run: make build-and-push-signoz-schema-migrator
      - name: Set docker tag environment without v prefix
        run: |
          if [ '${{ steps.branch-name.outputs.is_tag }}' == 'true' ]; then
            tag="${{ steps.branch-name.outputs.tag }}"
            tag="${tag:1}"
            echo "DOCKER_TAG=$tag" >> $GITHUB_ENV
          fi
      - name: Build artifacts for arm64/amd64
        run: make build-all
      - name: Build and push docker image without v prefix
        run: make build-and-push-signoz-schema-migrator
